daysUntilStale: 30
daysUntilClose: 7
exemptLabels:
  - meta
staleLabel: inactive
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: >
  This issue is being automatically closed due to inactivity. Please feel to re-open.
